use_frameworks!

platform :ios, '8.0'

target 'GSWebKitViewController_Example' do
  pod 'GSWebKitViewController', :path => '../'

  target 'GSWebKitViewController_Tests' do
    inherit! :search_paths

    
  end
end
